### ISSUE TITLE
The app crashes when scrolling the home page.

### ISSUE THREAD

**Issue by superrnovae** [PoomSmart/YTAutoFullScreen#1]
The tweak is causing the application to crash.      

Here are the steps to reproduce:    
**1.** Scroll the home page.
**2.** Go back to the top.
**3.** Pull down to refresh
**4.** Scroll the home page again

I can reproduce it every time. Sometimes it takes 2 to 3 pull downs, but eventually the app always crashes.
    
Edit: Can't reproduce after disabling autoplay during navigation. I think it happens because home page previews don't have value for key _UIDelegate so we crash.

Crash log: 
[YouTube-2021-12-21-230626.txt](https://github.com/PoomSmart/YTAutoFullScreen/files/7758749/YouTube-2021-12-21-230626.txt)

**Comment by PoomSmart** [comment]
@bakedpotato191 Do you think wrapping the full-screen code with try-catch can fix this issue?

**Comment by superrnovae** [comment]
@PoomSmart We will still be leaking memory, so I don't think that is the best idea.

**Comment by PoomSmart** [comment]
@bakedpotato191 This version I use `NSTimer` and inside a new method instead. See if it still crashes your device.
[com.ps.ytautofullscreen_1.0.3_iphoneos-arm.deb.zip](https://github.com/PoomSmart/YTAutoFullScreen/files/7762022/com.ps.ytautofullscreen_1.0.3_iphoneos-arm.deb.zip)

**Comment by superrnovae** [comment]
> See if it still crashes your device.

No. It doesn't crash anymore. Works like a charm. Thank you!
